name: on_mall
description: "On Mall."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  


  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  flutter_dotenv: ^5.2.1
  animate_do: ^3.3.4
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  shared_preferences: ^2.5.1
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.11.0
  animated_toggle_switch: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_bloc: ^9.0.0
  freezed: ^2.5.7
  connectivity_plus: ^6.1.2
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/core/
    - assets/images/icons/
    - lang/ar.json
    - lang/en.json
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
          style: italic

    # English font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
flutter_intl:
  enabled: true
