// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXArguAHw1s8BxVIRexZqijj_V6HHtZg',
    appId: '1:579272861344:web:73dbe57a08aafda99e8bc5',
    messagingSenderId: '579272861344',
    projectId: 'onmall-8fe61',
    authDomain: 'onmall-8fe61.firebaseapp.com',
    storageBucket: 'onmall-8fe61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Zy-IddgV0qXSV-RMNVAsS5xYIfHkCLQ',
    appId: '1:579272861344:android:f97a16c319b7a1229e8bc5',
    messagingSenderId: '579272861344',
    projectId: 'onmall-8fe61',
    storageBucket: 'onmall-8fe61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsbjKXHb131FN0PSf_C9D98Qho9Lva04',
    appId: '1:579272861344:ios:6c09cd3945e724829e8bc5',
    messagingSenderId: '579272861344',
    projectId: 'onmall-8fe61',
    storageBucket: 'onmall-8fe61.firebasestorage.app',
    iosBundleId: 'com.example.onMall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACsbjKXHb131FN0PSf_C9D98Qho9Lva04',
    appId: '1:579272861344:ios:6c09cd3945e724829e8bc5',
    messagingSenderId: '579272861344',
    projectId: 'onmall-8fe61',
    storageBucket: 'onmall-8fe61.firebasestorage.app',
    iosBundleId: 'com.example.onMall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoXArguAHw1s8BxVIRexZqijj_V6HHtZg',
    appId: '1:579272861344:web:f428470f16ac54ea9e8bc5',
    messagingSenderId: '579272861344',
    projectId: 'onmall-8fe61',
    authDomain: 'onmall-8fe61.firebaseapp.com',
    storageBucket: 'onmall-8fe61.firebasestorage.app',
  );
}
